/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package src.main.java.demo;
import java.net.MalformedURLException;
public class App {
  
    public void getGreeting() throws InterruptedException, MalformedURLException {
        BookMyShow tests = new BookMyShow(); // Initialize your test class
        //TODO: call your test case functions one after other here
        tests.testcase01();
        //END Tests
        tests.endTest(); // End your test by clearning connections and closing browser
    }
    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        new App().getGreeting();
    }
}
